services:
  portainer:
    profiles: ["portainer"]
  matter_server:
    profiles: ["matter"]
  appdaemon:
    profiles: ["appdaemon"]
  zigbee2mqtt:
    profiles: ["zigbee"]
  ai-bridge:
    profiles: ["agent-bridge"]
